# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend/Backend
    - name: Build
      run: dotnet build Backend.sln --no-restore
      working-directory: backend/Backend
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: backend/SE_Platzverwaltung.Tests
    - name: Publish
      run: dotnet publish Backend.sln -c Release -o ./publish
      working-directory: backend/Backend
    - name: Upload published artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-backend
        path: backend/Backend/publish
